### ISSUE TITLE
Lỗi bị co màn hình

### ISSUE THREAD

**Issue by phuleethanh** [natsukagami/themis-web-interface#1]
Sau khi cài đặt thành công, chạy chương trình thì giao diện bị thu nhỏ lại =1/4 màn hình laptop. Như giao diện mobile. (máy mình win 10 x64)

**Comment by natsukagami** [comment]
Lỗi do khi giải nén, các link không được bung ra nên xảy ra thiếu file CSS và JS. Sẽ được fix cho phiên bản tiếp theo.

**Comment by natsukagami** [comment]
Các bạn có thể down lại file .zip mới, từ các phiên bản sau file zip sẽ không bị lỗi nữa.

**Comment by natsukagami** [comment]
Lỗi sẽ được sửa khi build file zip bằng lệnh `yarn build` kể từ a04d1b6f9a43940b548ec5da12ea9f505f3914b5.
