### ISSUE TITLE
[Feature] Hiện số bài trong queue

### ISSUE THREAD

**Issue by ndkimhao** [natsukagami/themis-web-interface#11]
Em đề xuất thêm 1 dòng hiện số bài trong queue, vì trường hợp có hàng trăm bài trong queue, nó cứ xoay mãi không biết là có đang chấm hay không.

**Comment by natsukagami** [comment]
Chắc chỉ cần đếm số file trong `data/submit` thôi nhỉ?

Nên implement như nào để tối ưu số lần readdir? Mình nghĩ có thể dùng watch.

**Comment by ndkimhao** [comment]
Dùng watch cần platform hỗ trợ thì mới có hiệu suất cao, em cũng ko biết fs.watch và fs.watchFile dùng API của HĐH hay là gọi thăm thư mục liên tục để phát hiện thay đổi.
Mình có thể cache số file trong thư mục ```submit```, khi request log file thì trả cái đó về chung luôn. Nếu khi request mà cache bị expire thì mình gọi readdir lại. Ưu điểm:
+ Số lần gọi bị giới hạn lại theo config, vd tối đa 1 lần / 1sec
+ Nếu ko ai truy cập web thì ko cần phải gọi readdir
