### ISSUE TITLE
Scoreboard not run

### ISSUE THREAD

**Issue by phuleethanh** [natsukagami/themis-web-interface#13]
Bảng điểm lúc được lúc không. Có lúc nộp bài rồi nhưng không báo điểm trên bảng điểm.

**Comment by phuleethanh** [comment]
![1](https://cloud.githubusercontent.com/assets/24895255/22090589/3a6a642e-de25-11e6-9583-f0655b30fc86.PNG)

**Comment by phuleethanh** [comment]
![2](https://cloud.githubusercontent.com/assets/24895255/22090594/40ee80be-de25-11e6-9f88-951af9945010.PNG)

**Comment by natsukagami** [comment]
Việc cập nhật tự động đã được cải tiến trong một số commit gần đây. Có lẽ lỗi này không còn nữa, mình sẽ close cái issue này. Nếu còn lỗi, hãy mở issue khác.

**Comment by hoangduong98998** [comment]
Lại là lỗi dấu chấm, dấu phẩy.
