### ISSUE TITLE
Bảng điểm lỗi

### ISSUE THREAD

**Issue by kc97ble** [natsukagami/themis-web-interface#18]
![untitled](https://cloud.githubusercontent.com/assets/7184368/26820636/b1207e0e-4acd-11e7-845d-21a56b733e86.png)

**Comment by natsukagami** [comment]
Lỗi điểm do tên bài viết hoa/thường...
Bản nào vậy anh

**Comment by kc97ble** [comment]
hỏi thầy Thuận nhé, anh thấy bug thì báo cáo thôi

@thầy Thuận: em đang report cái bug bảng điểm cho Nguyên ạ

2017-06-06 19:04 GMT+07:00 Natsu Kagami <notifications@github.com>:

**Comment by kc97ble** [comment]
bản cũ: tắt console đi, bật run lại bị double hiển thị kết quả các bài lên.

bản mới: chưa test kỹ lỗi này, nhưng có 1 lỗi bí hiểm là khi cài lên máy
của 1 cô giáo khác thì điểm tất cả các bài trên ranking đều 0 điểm hết mặc
dù nộp và chấm bình thường trên themis.

2017-06-07 0:22 GMT+07:00 Kiên Nguyễn Tiến Trung <kc97ble@gmail.com>:

**Comment by natsukagami** [comment]
Không biết thầy và cô đã thử bản v0.3.1 mới nhất chưa nhỉ? Bản này đã sửa lỗi trùng tên bài, đồng thời em đã viết lại hế thống bảng điểm.

**Comment by hoangduong98998** [comment]
Lỗi điểm và ranking đều 0 là do sử dụng dấu , là dấu thập phân thay vì dấu .
