### ISSUE TITLE
Bảng xếp hạng không hiện điểm

### ISSUE THREAD

**Issue by hoangduong98998** [natsukagami/themis-web-interface#19]
Ở giao diện nộp bài đã hiển thị điểm của mỗi bài.
<img src="http://i.imgur.com/NZOs8e3.png" />
Trong giao diện bảng xếp hạng không hiển thị điểm.
<img src="http://i.imgur.com/Ry63IPD.png" />

**Comment by natsukagami** [comment]
Do phần parse string thành số không expect dấu phẩy (`,`) thay cho dấu (`.`).

Có thể thấy trong đoạn log sau (gửi bởi @hoangduong98998):
```
admin‣COFFEE‣test16: 1,00
Thời gian ≈ 0,111824893 giây
```

Chưa biết đây là behaviour mới của Themis 1.9.x, hay chỉ do OP đổi kiểu số hiển thị trong Windows.
Hơi buồn vì hàm `Number()` của JS cùi quá. Sẽ fix trong bản tiếp theo.

**Comment by natsukagami** [comment]
Mình vừa tạo commit 82b4b22e7d3d355a351e47ea9f0225c0af72c421, có fix tuy nhiên chỉ có cho Regional  Settings của VN. Không có cách cụ thể nào để thỏa mãn bất cứ Regional Settings nào cả. Không biết có thể coi là ổn chưa nhỉ.

**Comment by hoangduong98998** [comment]
Themis chắc chỉ được dùng ở VN thôi, Nên nếu fix được theo chuẩn của VN là ổn rồi ạ.
