### ISSUE TITLE
Lỗi hiển thị column bên phải

### ISSUE THREAD

**Issue by phuleethanh** [natsukagami/themis-web-interface#2]
Column bên phải hiển thị không thấy text (Kể cả nút lệnh và log)

**Comment by natsukagami** [comment]
@phuleethanh bạn có screenshot không, attach vào issue cho mình xem với?

**Comment by phuleethanh** [comment]
Cột code: hơi nhỏ và gò bó sao ấy, nếu được mở rộng sang bên phải chuyển nút submit và log xuống dưới thì tuyệt

**Comment by phuleethanh** [comment]
![issue1](https://cloud.githubusercontent.com/assets/24895255/21612420/b0b9486c-d203-11e6-87dd-652f57275afc.PNG)

**Comment by natsukagami** [comment]
Bạn đang dùng firefox đúng không? 
Bạn thử mở bằng chrome xem có bị không.
Đồng thời hãy thử thay file `index.js` trong `public\js` bằng file mình đính kèm và thử lại server, xem vấn đề có được giải quyết không?

[index.js.zip](https://github.com/natsukagami/themis-web-interface/files/682535/index.js.zip)

**Comment by phuleethanh** [comment]
![issue2](https://cloud.githubusercontent.com/assets/24895255/21612954/c0fdefc8-d205-11e6-851c-a0f4910aa8ac.PNG)

**Comment by phuleethanh** [comment]
Dùng IE hay Edg vẫn bị, chrome chưa thử

**Comment by phuleethanh** [comment]
Sau khi thay file bạn gửi thì lỗi hiển thị được khắc phục trên firefox, còn IE Edg Chrome đều bì lỗi như hình trên đó Nguyên ơi.
Riêng chrome mà nộp từ bài thứ 2 trở đi là lỗi hiển thị không còn nữa. OK

**Comment by natsukagami** [comment]
Trên máy mình thử với file index.js mới thì IE, Edge, Firefox và Chrome đều ok khi mở ra tuy nhiên riêng với Chrome thì bị như hình 2 khi xóa hết file đi tạo lại (F5 lại hết).

**Comment by natsukagami** [comment]
Mình xóa hẳn cột bên phải rồi, giờ giao diện sẽ trông như này
![trang ch - trnh chm themis - google chrome_4](https://cloud.githubusercontent.com/assets/9061737/21615553/935c78f4-d210-11e6-8584-e3d03f47a8b3.jpg)
![trang ch - trnh chm themis - google chrome_5](https://cloud.githubusercontent.com/assets/9061737/21615582/acbd36a8-d210-11e6-9c12-352ceb17a17d.jpg)
![trang ch - trnh chm themis - google chrome_6](https://cloud.githubusercontent.com/assets/9061737/21615605/cad284fe-d210-11e6-86ff-a859c00b7692.jpg)
