### ISSUE TITLE
Không hiển thị hết các file

### ISSUE THREAD

**Issue by hoangduong98998** [natsukagami/themis-web-interface#29]
Trong trường hợp đang soạn code thì không hiển thị tất cả các file
<img src="https://i.imgur.com/13bQpc8.png" />

Trong trường hợp có nhiều file thì không hiển thị file cuối cùng
<img src="https://i.imgur.com/6VyNfoW.png" />

**Comment by natsukagami** [comment]
Cái cột bên trái có cơ chế scroll độc lập với phần còn lại của trang web. Ở trường hợp đầu chỉ cần di chuột vào cột bên trái rồi cuộn xuống?

Việc bị thiếu file là do bạn thêm 1 dòng nữa vào footer của trang nên độ cao không như ban đầu, làm hiển thị thiếu.

**Comment by hoangduong98998** [comment]
Cảm ơn ạ!
