### ISSUE TITLE
Không check case-sensitive

### ISSUE THREAD

**Issue by dungwinux** [natsukagami/themis-web-interface#30]
![capture](https://user-images.githubusercontent.com/23451424/35433536-57ae6f60-02b6-11e8-9e3c-61129ac42fc6.PNG)
Khi nộp nhiều bài với kiểu viết hoa khác nhau, Themis vẫn sẽ compile và chấm điểm như thường nhưng Web interface không lọc tên file nên các tài khoản có thể cộng dồn điểm.
Team **__kali** đã cộng dồn điểm bài BALANCED như trên.

Found by: @minhducsun2002, @dungwinux

**Comment by natsukagami** [comment]
Nếu mình không nhầm thì issue này đã được fix ở bản mới nhất, bạn thử download bản mới nhất thử xem!
