### ISSUE TITLE
Cách cài themis web interface.

### ISSUE THREAD

**Issue by ghost** [natsukagami/themis-web-interface#31]
Chào anh Nguyên, em là Dương.

Anh có thể chỉ em cách cài đúng bản themis web interface này được ko ạ, em đã thử tải source code về, cài và thiết lập node.js nhưng không xong ạ, (nó cứ bắt phải configure files), nên em chưa thể cài và start server được.

Mong anh chỉ giáo ạ !

Dương Nguyễn

**Comment by natsukagami** [comment]
Em đọc kỹ README.md nhé
