### ISSUE TITLE
Lỗi giao diện khi tên file dài

### ISSUE THREAD

**Issue by ndkimhao** [natsukagami/themis-web-interface#8]
Khi tên file dài, khung điểm sẽ bị nhảy xuống dưới
![image](https://cloud.githubusercontent.com/assets/7188260/21762423/2c479052-d68b-11e6-94f5-33a5cff0d07a.png)

**Comment by natsukagami** [comment]
Có thể fix bằng responsive font size chăng?

**Comment by ndkimhao** [comment]
Em nghĩ nếu nó bị thu nhỏ quá mức thi có thể cắt khúc cuối file thành "...", còn full tên file thì để dưới dạng tooltip khi rê chuột qua mới thấy
